name: Continous Integration

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
      - master
      - development

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Run tests
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Create CI Status File
        if: success()
        run: |
          echo "success" > ci_status.txt
        # Use l'action upload-artifact for create artefact

      - name: Check status
        run: |
          ls -a
      - name: Upload CI Status Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ci_status
          path: ci_status.txt
