name: Quality Code

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
      - master
      - development

jobs:
  test:
    name: Quality Code
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Test quality code
        run: npm run lint

      - name: Create Lint Status File
        if: success()
        run: |
          echo "success" > lint_status.txt
        # Use l'action upload-artifact for create artefact
      - name: Upload Lint Status Artifact
        uses: actions/upload-artifact@v3
        with:
          name: lint_status
          path: lint_status.txt
