name: Main Workflow

on:
  workflow_run:
    workflows: ["Continous Integration", "Quality Code"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        run: |
          # Insérez ici les commandes pour le déploiement vers GitHub Pages
          # Par exemple, vous pouvez utiliser les pages GitHub Actions de GitHub
