name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  test_and_coverage:
    name: Test and Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Display Current Directory
        run: |
          pwd  # Command to print the current directory
          ls   # List the files in the current directory
        # Rest of your workflow steps
        continue-on-error: true # Continue even if this step fails

      - name: Run Tests and Code Coverage
        uses: ./.github/workflows/ci.yml
        continue-on-error: true # Continue even if this step fails

  quality_checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Display Current Directory
        run: |
          pwd  # Command to print the current directory
          ls   # List the files in the current directory
        # Rest of your workflow steps
        continue-on-error: true # Continue even if this step fails

      - name: Run linters and other code quality checks
        uses: ./.github/workflows/lint.yml
        continue-on-error: true # Continue even if this step fails
