name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  test_and_coverage:
    name: Test and Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests and Code Coverage
        uses: ./.github/workflows/ci.yml

  quality_checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Run Code Quality Checks
        uses: ./.github/workflows/lint.yml
