name: Main Workflow

on:
  workflow_run:
    workflows: ["Continous Integration", "Quality Code"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Lint Status Artifact
        uses: actions/download-artifact@v3
        with:
          name: lint_status # Le même nom que vous avez donné lors de l'upload dans le workflow "Quality Code"
          path: .

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Check Files
        run: |
          ls -a
        shell: bash
