name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  ci_cd:
    name: Continous Integration & Continous Deployement
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Check CI and Lint Workflow Results
        run: |
          cd ./github/workflows/
          ls -a
          if [ -f .github/workflows/ci_status.txt ] && [ "$(cat .github/workflows/ci_status.txt)" == "success" ]; then
            echo "CI Workflow succeeded."
          else
            echo "CI Workflow failed or not found."
          fi

          if [ -f .github/workflows/lint_status.txt ] && [ "$(cat .github/workflows/lint_status.txt)" == "success" ]; then
            echo "Lint Workflow succeeded."
          else
            echo "Lint Workflow failed or not found."
          fi
        working-directory: ${{ github.workspace }}
        continue-on-error: true # Continue even if this step fails
