name: Main Workflow

on:
  workflow_run:
    workflows: ["Continous Integration", "Quality Code"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Set Git user information
        run: |
          git config --global user.name ${{ secrets.GIT_USERNAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
        shell: bash

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: npm run deploy
