name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  test_and_coverage:
    name: Test and Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Tests and Code Coverage
        uses: ./.github/workflows/ci.yml
        env:
          WORKFLOW_STATUS: ${{ job.status }}

  quality_checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters and other code quality checks
        uses: ./.github/workflows/lint.yml
        env:
          WORKFLOW_STATUS: ${{ job.status }}
