name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  test_and_coverage:
    name: Test and Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Tests and Code Coverage
        uses: ./.github/workflows/ci.yml

  quality_checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters and other code quality checks
        uses: ./.github/workflows/lint.yml

  # deploy:
  #   name: Deployment
  #   runs-on: ubuntu-latest
  #   needs: [test_and_coverage, quality_checks]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 18

  #     - name: Install Node.js dependencies
  #       run: npm ci

  #     - name: Deploy to Production
  #       run: |
  #         if [ ${{ job.test_and_coverage.outcome }} == 'success' ] && [ ${{ job.quality_checks.outcome }} == 'success' ]; then
  #           # Déployez votre application car les tests et la qualité de code ont réussi
  #           # Ajoutez vos commandes de déploiement ici
  #         else
  #           echo "Les tests ou la qualité de code ont échoué. Le déploiement est annulé."
  #         fi
