name: Main Workflow

on:
  workflow_run:
    workflows: ["Continous Integration", "Quality Code"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check File tree
        run: |
          ls -a
